### PR TITLE
Add support for building against cortexa15

### PR DESCRIPTION
**Pull request by hoefling**
Signed-off-by: Oleg Höfling <oleg.hoefling@gmail.com>

### CODE REVIEW

**Comment by honnibal** [comment]
Thanks! I think I need to make some updates to the Azure Pipelines. But appreciate the build file.

**Comment by hoefling** [comment]
Sure, glad if this helps. Having a `cortexa15` config would make building platform-specific wheels for Raspberry Pi 2 & 3 a lot easier.

**Comment by svlandeg** [comment]
Hi @hoefling, we fixed some unrelated issues with the test suite - could you merge `explosion:master` into your branch? That will automatically update this PR and should restart the tests, which will then hopefully go green ;-)

**Comment by hoefling** [comment]
@svlandeg I've rebased onto current master, CI looking good!

**Pull request merged**
