### PR TITLE
simple parallel build

### LINKED ISSUE #28: support parallel builds with `setup.py build -j10`
When I try to do a parallel build with `setup.py build -j10` I still only get one gcc process being run at a time, which means that the build takes a while longer than I would like. It would be great to have support for parallel builds so they take less time.

### PR DESCRIPTION
**Pull request by dimaqq**
Compile `.c` → `.o` in parallel to close #28 

Tries to use as many cores as available, naively, but already better than one file at a time:

Screenshot 2021-02-25 at 12 56 26

### CODE REVIEW

**Comment by adrianeboyd** [comment]
If we do this (I still need to look at the details), instead of the max cpu count we should use the `-j` option which is stored as `self.parallel` in `ExtensionBuilder`.

**Comment by dimaqq** [comment]
re: configurability
I don't mind at all if you take over this PR :)

re: automated checks...
I see that Python 2.7 and 3.5 checks are still configured for this project, however, the only wheels are only available for 3.6 ~ 3.9 on PYPI.
I'm not sure what Python versions should ultimately be supported.
I think that f-string is the only "new" feature in the proposed change.

**Comment by adrianeboyd** [comment]
We have a wider range of python version compatibility than published wheels in a lot of cases, for instance we've kept spacy v2.x compatible with python 2.7 even though we haven't published python 2.7 wheels for a while.

I have to look a bit more into the details about what kind of multiprocessing setup makes sense, since I'd rather have slow builds than broken/brittle builds.

And probably it does make sense to do this in combination with an environment variable so this also works with `pip` and other build systems, something like numpy's `NPY_NUM_BUILD_JOBS`.

**Comment by dimaqq** [comment]
This has probably gotten stale, feel free to close.

**Pull request closed without merging**
